// Author: Anuj Dev (B00900887)

export const SET_TOKEN = "SET_TOKEN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_ID = "SET_USER_ID";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const LOGOUT = "LOGOUT";
export const SET_ROOMMATE_LISTINGS = "SET_ROOMMATE_LISTINGS";
export const SET_EDIT_LISTING_DETAILS = "SET_EDIT_LISTING_DETAILS";
